import { useState } from "react";
import { Calendar, Clock, CalendarCheck, Copy, CheckCircle2, DollarSign } from "lucide-react";

import { Button } from "@/components/ui/button";
import { TimelineResult, formatDate, formatDateShort } from "../helpers/timeline-calculator";

interface TimelineResultsProps {
  result: TimelineResult;
  totalHours: number;
}

const CURRENCY_SYMBOLS: Record<string, string> = {
  USD: "$",
  EUR: "€",
  GBP: "£",
  CAD: "$",
  AUD: "$",
  INR: "₹",
  JPY: "¥",
};

function formatCurrency(amount: number, currency: string): string {
  const symbol = CURRENCY_SYMBOLS[currency] || "$";
  return `${symbol}${amount.toLocaleString("en-US", {
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  })}`;
}

export function TimelineResults({ result, totalHours }: TimelineResultsProps) {
  console.log("Rendering TimelineResults with result:", result, "and totalHours:", totalHours);
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    let summary = `📊 Project Timeline Estimate

Project Total Hours: ${totalHours} hours
Adjusted Hours: ${result.adjustedHours} hours
Duration: ${result.durationText} (${result.totalWorkingDays} days)
Estimated Delivery Date: ${formatDate(result.estimatedCompletionDate)}`;

    if (result.budget) {
      const b = result.budget;
      summary += `
Total Project Cost: ${formatCurrency(b.totalCost, b.currency)}`;
    }

    summary += `

Generated by Project Timeline Estimator`;

    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      // Fallback or ignore clipboard errors silently
    }
  };

  return (
    <div className="flex flex-col md:flex-row gap-4">
      {/* Timeline Results Card */}
      <section
        role="region"
        aria-labelledby="timeline-estimate-heading"
        className="flex-1 result-card animate-fade-in space-y-6"
      >
        <header className="flex items-center justify-between">
          <h2 id="timeline-estimate-heading" className="text-lg font-semibold text-foreground">
            Timeline Estimate
          </h2>
          <div className="flex items-center gap-2">
            <Button
              type="button"
              variant="secondary"
              size="sm"
              onClick={handleCopy}
              aria-label="Copy timeline summary"
              className="gap-2"
            >
              {copied ? (
                <>
                  <CheckCircle2 className="h-4 w-4 text-success" />
                  <span>Copied</span>
                </>
              ) : (
                <>
                  <Copy className="h-4 w-4" />
                  <span>Copy Summary</span>
                </>
              )}
            </Button>
            <span role="status" aria-live="polite" className="sr-only">
              {copied ? "Summary copied to clipboard" : ""}
            </span>
          </div>
        </header>

        {/* Main Stats Grid */}
        <dl className="grid grid-cols-2 gap-4">
          <div>
            <dt className="flex items-center gap-2 text-muted-foreground">
              <Clock className="h-4 w-4" />
              <span className="stat-label">Adjusted Hours</span>
            </dt>
            <dd className="stat-value">{result.adjustedHours}h</dd>
          </div>

          <div>
            <dt className="flex items-center gap-2 text-muted-foreground">
              <Calendar className="h-4 w-4" />
              <span className="stat-label">Working Days</span>
            </dt>
            <dd className="stat-value">{result.totalWorkingDays}</dd>
          </div>
        </dl>

        {/* Duration */}
        <dl className="rounded-lg bg-secondary/50 p-4 space-y-1" aria-labelledby="duration-label">
          <dt id="duration-label" className="stat-label">
            Estimated Duration
          </dt>
          <dd className="text-2xl font-bold text-foreground tracking-tight">
            {result.durationText}
          </dd>
        </dl>

        {/* Completion Date */}
        <dl className="space-y-1">
          <dt className="flex items-center gap-2">
            <CalendarCheck className="h-5 w-5 text-primary" />
            <span className="font-medium text-foreground">Completion Date</span>
          </dt>
          <dd className="text-xl font-semibold text-foreground">
            <time dateTime={(result.estimatedCompletionDate as Date).toISOString()}>
              {formatDate(result.estimatedCompletionDate)}
            </time>
          </dd>
        </dl>

        {/* Delivery Range */}
        <dl className="border-t border-border pt-3 space-y-2">
          <p className="text-sm font-medium text-muted-foreground uppercase tracking-wide">
            Delivery Range
          </p>
          <div className="flex flex-col sm:flex-row gap-3">
            <div className="flex-1 rounded-lg border border-border bg-card py-2 px-3">
              <dt className="text-xs text-muted-foreground mb-1">Optimistic (No buffer)</dt>
              <dd className="font-semibold text-foreground">
                {formatDateShort(result.optimisticDate)}
              </dd>
            </div>
            <div className="flex-1 rounded-lg border-2 border-primary/30 bg-highlight/50 py-2 px-3">
              <dt className="text-xs text-highlight-foreground mb-1">Safe Delivery With buffer</dt>
              <dd className="font-semibold text-foreground">{formatDateShort(result.safeDate)}</dd>
            </div>
          </div>
        </dl>
      </section>

      {/* Budget Summary Card */}
      {result.budget && (
        <section
          role="region"
          aria-labelledby="budget-summary-heading"
          className="flex-1 result-card animate-fade-in space-y-6"
        >
          <div className="flex items-center gap-2">
            <DollarSign className="h-5 w-5 text-primary" />
            <h3 id="budget-summary-heading" className="text-lg font-semibold text-foreground">
              Budget Summary
            </h3>
          </div>

          {/* Total Cost */}
          <div className="rounded-lg bg-secondary/50 p-4 space-y-1">
            <p className="stat-label">Total Project Cost</p>
            <p className="text-3xl font-bold text-foreground tracking-tight">
              {formatCurrency(result.budget.totalCost, result.budget.currency)}
            </p>
          </div>

          {/* Cost Range - Only for Hourly */}
          {result.budget.isHourly && (
            <div className="space-y-3">
              <p className="text-sm font-medium text-muted-foreground uppercase tracking-wide">
                Cost Range
              </p>
              <div className="flex flex-col sm:flex-row gap-3">
                <div className="flex-1 rounded-lg border border-border bg-card p-3">
                  <p className="text-xs text-muted-foreground mb-1">Optimistic (No buffer)</p>
                  <p className="font-semibold text-foreground">
                    {formatCurrency(result.budget.optimisticCost, result.budget.currency)}
                  </p>
                </div>
                <div className="flex-1 rounded-lg border-2 border-primary/30 bg-highlight/50 p-3">
                  <p className="text-xs text-highlight-foreground mb-1">Safe (With buffer)</p>
                  <p className="font-semibold text-foreground">
                    {formatCurrency(result.budget.safeCost, result.budget.currency)}
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* Monthly Cost */}
          <div className="border-t border-border pt-4 space-y-3">
            <p className="text-sm font-medium text-muted-foreground uppercase tracking-wide">
              Average Monthly Cost
            </p>
            <div className="flex flex-col sm:flex-row gap-3">
              <div className="flex-1 rounded-lg border border-border bg-card p-3">
                <p className="text-xs text-muted-foreground mb-1">Optimistic (No buffer)</p>
                <p className="font-semibold text-foreground">
                  {formatCurrency(result.budget.monthlyOptimistic, result.budget.currency)}
                </p>
              </div>
              <div className="flex-1 rounded-lg border border-border bg-card p-3">
                <p className="text-xs text-muted-foreground mb-1">Safe (With buffer)</p>
                <p className="font-semibold text-foreground">
                  {formatCurrency(result.budget.monthlySafe, result.budget.currency)}
                </p>
              </div>
            </div>
          </div>

          {/* Weekly Cost - Only for Fixed Price */}
          {!result.budget.isHourly && (
            <div className="border-t border-border pt-4 space-y-3">
              <p className="text-sm font-medium text-muted-foreground uppercase tracking-wide">
                Weekly Cost
              </p>
              <div className="flex flex-col sm:flex-row gap-3">
                <div className="flex-1 rounded-lg border border-border bg-card p-3">
                  <p className="text-xs text-muted-foreground mb-1">Optimistic (No buffer)</p>
                  <p className="font-semibold text-foreground">
                    {formatCurrency(result.budget.weeklyOptimistic, result.budget.currency)}
                  </p>
                </div>
                <div className="flex-1 rounded-lg border border-border bg-card p-3">
                  <p className="text-xs text-muted-foreground mb-1">Safe (With buffer)</p>
                  <p className="font-semibold text-foreground">
                    {formatCurrency(result.budget.weeklySafe, result.budget.currency)}
                  </p>
                </div>
              </div>
            </div>
          )}
        </section>
      )}
    </div>
  );
}
