import { useState } from "react";
import { Calendar, Clock, CalendarCheck, Copy, CheckCircle2, DollarSign } from "lucide-react";

import { Button } from "@/components/ui/button";
import { TimelineResult, formatDate, formatDateShort } from "../helpers/timeline-calculator";

interface TimelineResultsProps {
  result: TimelineResult;
  totalHours: number;
}

const CURRENCY_SYMBOLS: Record<string, string> = {
  USD: "$",
  EUR: "€",
  GBP: "£",
  CAD: "$",
  AUD: "$",
  INR: "₹",
  JPY: "¥",
};

function formatCurrency(amount: number, currency: string): string {
  const symbol = CURRENCY_SYMBOLS[currency] || "$";
  return `${symbol}${amount.toLocaleString("en-US", {
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  })}`;
}

export function TimelineResults({ result, totalHours }: TimelineResultsProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    let summary = `📊 Project Timeline Estimate

📥 Input:
• Total Hours: ${totalHours}
• Adjusted Hours (with buffer): ${result.adjustedHours}

📅 Timeline:
• Working Days Required: ${result.totalWorkingDays}
• Duration: ${result.durationText}
• Estimated Completion: ${formatDate(result.estimatedCompletionDate)}

📍 Delivery Range:
• Optimistic (no buffer): ${formatDate(result.optimisticDate)}
• Safe (with buffer): ${formatDate(result.safeDate)}`;

    if (result.budget) {
      const b = result.budget;
      summary += `

💰 Budget Summary:
• Total Project Cost: ${formatCurrency(b.totalCost, b.currency)}
• Optimistic Cost: ${formatCurrency(b.optimisticCost, b.currency)}
• Safe Cost: ${formatCurrency(b.safeCost, b.currency)}
• Monthly (Optimistic): ${formatCurrency(b.monthlyOptimistic, b.currency)}
• Monthly (Safe): ${formatCurrency(b.monthlySafe, b.currency)}`;
    }

    summary += `

Generated by Project Timeline Estimator`;

    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex flex-col md:flex-row gap-4">
      {/* Timeline Results Card */}
      <div className="flex-1 result-card animate-fade-in space-y-6">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold text-foreground">Timeline Estimate</h2>
          <Button variant="secondary" size="sm" onClick={handleCopy} className="gap-2">
            {copied ? (
              <>
                <CheckCircle2 className="h-4 w-4 text-success" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="h-4 w-4" />
                Copy Summary
              </>
            )}
          </Button>
        </div>

        {/* Main Stats Grid */}
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2 text-muted-foreground">
              <Clock className="h-4 w-4" />
              <span className="stat-label">Adjusted Hours</span>
            </div>
            <p className="stat-value">{result.adjustedHours}h</p>
          </div>

          <div className="space-y-1">
            <div className="flex items-center gap-2 text-muted-foreground">
              <Calendar className="h-4 w-4" />
              <span className="stat-label">Working Days</span>
            </div>
            <p className="stat-value">{result.totalWorkingDays}</p>
          </div>
        </div>

        {/* Duration */}
        <div className="rounded-lg bg-secondary/50 p-4 space-y-1">
          <p className="stat-label">Estimated Duration</p>
          <p className="text-2xl font-bold text-foreground tracking-tight">{result.durationText}</p>
        </div>

        {/* Completion Date */}
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <CalendarCheck className="h-5 w-5 text-primary" />
            <span className="font-medium text-foreground">Completion Date</span>
          </div>
          <p className="text-xl font-semibold text-foreground">
            {formatDate(result.estimatedCompletionDate)}
          </p>
        </div>

        {/* Delivery Range */}
        <div className="border-t border-border pt-3 space-y-2">
          <p className="text-sm font-medium text-muted-foreground uppercase tracking-wide">
            Delivery Range
          </p>
          <div className="flex flex-col sm:flex-row gap-3">
            <div className="flex-1 rounded-lg border border-border bg-card py-2 px-3">
              <p className="text-xs text-muted-foreground mb-1">Optimistic (No buffer)</p>
              <p className="font-semibold text-foreground">
                {formatDateShort(result.optimisticDate)}
              </p>
            </div>
            <div className="flex-1 rounded-lg border-2 border-primary/30 bg-highlight/50 py-2 px-3">
              <p className="text-xs text-highlight-foreground mb-1">Safe Delivery With buffer</p>
              <p className="font-semibold text-foreground">{formatDateShort(result.safeDate)}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Budget Summary Card */}
      {result.budget && (
        <div className="flex-1 result-card animate-fade-in space-y-6">
          <div className="flex items-center gap-2">
            <DollarSign className="h-5 w-5 text-primary" />
            <h2 className="text-lg font-semibold text-foreground">Budget Summary</h2>
          </div>

          {/* Total Cost */}
          <div className="rounded-lg bg-secondary/50 p-4 space-y-1">
            <p className="stat-label">Total Project Cost</p>
            <p className="text-3xl font-bold text-foreground tracking-tight">
              {formatCurrency(result.budget.totalCost, result.budget.currency)}
            </p>
          </div>

          {/* Cost Range - Only for Hourly */}
          {result.budget.isHourly && (
            <div className="space-y-3">
              <p className="text-sm font-medium text-muted-foreground uppercase tracking-wide">
                Cost Range
              </p>
              <div className="flex flex-col sm:flex-row gap-3">
                <div className="flex-1 rounded-lg border border-border bg-card p-3">
                  <p className="text-xs text-muted-foreground mb-1">Optimistic (No buffer)</p>
                  <p className="font-semibold text-foreground">
                    {formatCurrency(result.budget.optimisticCost, result.budget.currency)}
                  </p>
                </div>
                <div className="flex-1 rounded-lg border-2 border-primary/30 bg-highlight/50 p-3">
                  <p className="text-xs text-highlight-foreground mb-1">Safe (With buffer)</p>
                  <p className="font-semibold text-foreground">
                    {formatCurrency(result.budget.safeCost, result.budget.currency)}
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* Monthly Cost */}
          <div className="border-t border-border pt-4 space-y-3">
            <p className="text-sm font-medium text-muted-foreground uppercase tracking-wide">
              Average Monthly Cost
            </p>
            <div className="flex flex-col sm:flex-row gap-3">
              <div className="flex-1 rounded-lg border border-border bg-card p-3">
                <p className="text-xs text-muted-foreground mb-1">Optimistic (No buffer)</p>
                <p className="font-semibold text-foreground">
                  {formatCurrency(result.budget.monthlyOptimistic, result.budget.currency)}
                </p>
              </div>
              <div className="flex-1 rounded-lg border border-border bg-card p-3">
                <p className="text-xs text-muted-foreground mb-1">Safe (With buffer)</p>
                <p className="font-semibold text-foreground">
                  {formatCurrency(result.budget.monthlySafe, result.budget.currency)}
                </p>
              </div>
            </div>
          </div>

          {/* Weekly Cost - Only for Fixed Price */}
          {!result.budget.isHourly && (
            <div className="border-t border-border pt-4 space-y-3">
              <p className="text-sm font-medium text-muted-foreground uppercase tracking-wide">
                Weekly Cost
              </p>
              <div className="flex flex-col sm:flex-row gap-3">
                <div className="flex-1 rounded-lg border border-border bg-card p-3">
                  <p className="text-xs text-muted-foreground mb-1">Optimistic (No buffer)</p>
                  <p className="font-semibold text-foreground">
                    {formatCurrency(result.budget.weeklyOptimistic, result.budget.currency)}
                  </p>
                </div>
                <div className="flex-1 rounded-lg border border-border bg-card p-3">
                  <p className="text-xs text-muted-foreground mb-1">Safe (With buffer)</p>
                  <p className="font-semibold text-foreground">
                    {formatCurrency(result.budget.weeklySafe, result.budget.currency)}
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
